### ISSUE TITLE
Figure out what to do with the margin at the bottom of the content area

### ISSUE THREAD

**Issue by ericras** [unlcms/unl_five#53]
unl/wdntemplates has this CSS that is giving us whitespace at the bottom of the content area

```css
.unl .dcf-main-content > :last-child:not(.dcf-bleed) {
  margin-bottom: 3.16em;
}
```
Should we do this?
`<div class="region region-content dcf-bleed dcf-wrapper">`
